### ISSUE TITLE
Cached walks

### ISSUE THREAD

**Issue by theogf** [adolgert/BijectiveHilbert.jl#22]
Would that makes sense to have a function that would prestore the walks when the algorithm is called repeatedly?

I have a usecase where I sort colors using the walk and when using a cached lookup table, I get a very large speedup.

**Comment by adolgert** [comment]
Hi! I'm sorry I didn't answer this sooner. I think you might get good results with a technique called memoization (search "julia memoize". It's a macro that records a function's input and output and automatically caches every call. You would totally get a large speedup. It's funny that these functions are supposed to be so fast because they are bit-shifting and very type-stable, but memoization still really helps.

**Comment by theogf** [comment]
Thanks for the answer! I just ended up using a `Dict` as cache and it worked great. Closing the issue!
